version: '3.4'

services:
  productmicroservice:
    image: ${DOCKER_REGISTRY-}productmicroservice
    build:
      context: .
      dockerfile: ProductMicroservice/Dockerfile
  #  depends_on:
  #          - db

  #db:
  #  image: "mcr.microsoft.com/mssql/server"
  #  extra_hosts:
  #  - "localhost:192.168.5.2"


